In [1]:
inmport numpy as np

SyntaxError: invalid syntax (1046579179.py, line 1)

In [2]:
import numpy as np

In [3]:
x=np.zeros((3,4))

In [4]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
x= np.ones((2, 3, 4), dtype=np.int16)

In [6]:
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
x=np.arange(10, 25, 5)

In [8]:
x

array([10, 15, 20])

In [9]:
x=np.linspace(0, 2, 9)

In [10]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
x=np.full((2, 2), 7)

In [12]:
x

array([[7, 7],
       [7, 7]])

In [13]:
x=np.random.rand(2, 2)

In [14]:
x

array([[0.29434626, 0.57022499],
       [0.39944495, 0.19413955]])

In [15]:
x=np.eye(2)

In [16]:
x

array([[1., 0.],
       [0., 1.]])

In [20]:
a=np.array([10, 20, 30, 40, 50])

In [21]:
a

array([10, 20, 30, 40, 50])

In [22]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

In [23]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.transpose(b)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
c=np.array([1,2,3,4])

In [26]:
np.subtract(a,c)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [27]:
d=np.array([1,2,3,4,5])

In [28]:
np.subtract(a,d)

array([ 9, 18, 27, 36, 45])

In [29]:
 np.add(d,a) 

array([11, 22, 33, 44, 55])

In [30]:
 np.divide(a,d)

array([10., 10., 10., 10., 10.])

In [31]:
 np.multiply(a,d) 

array([ 10,  40,  90, 160, 250])

In [32]:
 np.exp(b) 

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [33]:
 np.sqrt(b) 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
 a.sum() 

np.int64(150)